### ISSUE TITLE
obs接口obs_head_bucket 返回OBS_STATUS_HttpErrorUnknown

### ISSUE THREAD

**Issue by yian-chen** [huaweicloud/huaweicloud-sdk-c-obs#14]
### 问题现象
代码中obs_head_buchet接口，刚开始的时，可以返回正确的值，一段时间后，就报错: `OBS_STATUS_HttpErrorUnknown`

### 问题排查
检查了option的内容，发现报错前和报错后，option没有区别，排除参数设置等人为错误

### 代码片段
![image](https://user-images.githubusercontent.com/11450967/91834337-7b7a4f80-ec7a-11ea-9caa-0ca7f295d062.png)

**Comment by yanwenb** [comment]
请您查看下run.log里的报错信息，以定位问题所在
