### ISSUE TITLE
创建并行文件系统桶报错段错误 (核心已转储)

### ISSUE THREAD

**Issue by c005machao5** [huaweicloud/huaweicloud-sdk-c-obs#16]
段错误 (核心已转储)
machao@machao-VirtualBox:~/mwx/OBS/huaweicloud-obs-sdk-c-linux/build$ gdb ./OBS
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./OBS...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/machao/mwx/OBS/huaweicloud-obs-sdk-c-linux/build/OBS
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
11111111111----------
22222222222
333333333333333333
[New Thread 0x7ffff4a78700 (LWP 9308)]
[Thread 0x7ffff4a78700 (LWP 9308) exited]

Thread 1 "OBS" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:301
301     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: 没有那个文件或目录.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:301
#1  0x00007ffff776884d in set_use_api_switch () from /home/machao/mwx/OBS/huaweicloud-obs-sdk-c-linux/lib/libeSDKOBS.so
#2  0x00007ffff7747d8d in create_pfs_bucket () from /home/machao/mwx/OBS/huaweicloud-obs-sdk-c-linux/lib/libeSDKOBS.so
#3  0x000055555555cffe in test_create_pfs_bucket ()
#4  0x000055555556666f in main ()
(gdb) quit
A debugging session is active.

        Inferior 1 [process 9304] will be killed.

Quit anyway? (y or n) y

**Comment by yanwenb** [comment]
您好，请确定在调用接口前进行了初始化。
