### ISSUE TITLE
OBS处理异常不能正确返回值

### ISSUE THREAD

**Issue by 1345520270** [huaweicloud/huaweicloud-sdk-c-obs#17]
ERROR_CODE 登录返回 NOT FOUND

**Comment by yanwenb** [comment]
您好，可以更详细的描述下您遇到的问题吗？

**Comment by 1345520270** [comment]
在使用C# obs sdk的时候 调试桶错误的时候不显示文档里提供的报错信息只显示404

**Comment by yanwenb** [comment]
https://support.huaweicloud.com/sdk-c-devg-obs/obs_20_1601.html
这里的错误码没有报错信息吗？

**Comment by 1345520270** [comment]
你这里定义的所有错误码 只会显示404

**Comment by yanwenb** [comment]
run.log日志中有没有相应的信息呢？
