### ISSUE TITLE
使用桶拥有者的AK/SK复制对象报签名不匹配

### ISSUE THREAD

**Issue by Liniaj** [huaweicloud/huaweicloud-sdk-c-obs#25]
使用桶拥有者的AK/SK复制其他账户上传的对象时，报错签名不匹配。
SDK C接口获取待复制对象的ACL，结果如下：
对象拥有者： FULL_CONTROL
桶拥有者账号ID： READ+ WRITE + READ_ACP + WRITE_ACP
All User: WRITE

我用桶拥有者账号重新创建了访问密钥，确认AK/SK没有问题。
我理解桶拥有者的账户类似于超级管理员，请问这个报错是什么原因？

**Comment by Liniaj** [comment]
我使用《对象存储服务OBS文档中》“Hearder中携带签名” 一篇中介绍的 C语言中签名的计算方法 和 签名计算工具获取的签名结果不一样，C语言中签名的计算方法和我使用的SDK C接口计算出的签名一致，但是和签名计算工具计算出的签名不一致。

**Comment by yanwenb** [comment]
您好，请问是调用其他接口没有问题，仅仅是在对这个其他账户上传的对象操作时会报错签名不匹配吗？
